### ISSUE TITLE
[feature] ec2 spring boot 배포 오류

### ISSUE THREAD

**Issue by pu2rile** [pknu-wap/GreenDay#19]
## 💥이슈 설명
우분투 접속 후 깃 클론 하고 깃 폴더에 빌드 파일 생성까지 완료되었지만 데이터베이스 설정 누락(에러 메시지 해석)으로 빌드 실패가 떴습니다...
하......................

## 📚할 일 목록
- [ ] 데이터베이스 설정 확인:
application.properties 또는 application.yml 파일에 데이터베이스 설정이 올바르게 되어 있는지 확인
```properties
spring.datasource.url=jdbc:mysql://localhost:3306/yourdatabase
spring.datasource.username=yourusername
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
```
application.yml 파일을 사용하는 경우:
```yaml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yourdatabase
    username: yourusername
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

```
- [ ] 데이터베이스 드라이버 의존성 추가:
build.gradle 파일에 데이터베이스 드라이버 의존성이 추가되어 있는지 확인
```groovy
dependencies {
    implementation 'mysql:mysql-connector-java'
}
```
그런 다음, gradle build 명령을 다시 실행하여 의존성을 다운로드

- [ ] 프로파일 활성화:
특정 프로파일에 데이터베이스 설정이 포함되어 있는 경우, 해당 프로파일을 활성화
application-dev.properties에 설정이 있는 경우:
```properties
spring.profiles.active=dev
```
 명령어로 실행 시:
```bash
 java -jar -Dspring.profiles.active=dev green_day_history-0.0.1-SNAPSHOT.jar
```
- [ ] 디버그 모드로 실행
```bash
java -jar green_day_history-0.0.1-SNAPSHOT.jar --debug
```

### 전체 과정 예시
1. application.properties 파일 설정:
```properties
spring.datasource.url=jdbc:mysql://localhost:3306/greendaydb
spring.datasource.username=greendayuser
spring.datasource.password=greendaypassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
```
2. build.gradle 파일 수정:
```groovy
dependencies {
    implementation 'mysql:mysql-connector-java'
    // 다른 의존성들...
}
```
3. Gradle 빌드:
```bash
./gradlew build
```
4. 애플리케이션 실행:
```bash
java -jar green_day_history-0.0.1-SNAPSHOT.jar
```

## 👀참고 사항
- 메인에 여태 개발한 코드를 머지해야 할 것 같습니다...?

## ⌛기한
~5/19
